before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-xetex
- chmod u+x ./travis/build.sh
- chmod u+x ./travis/publish.sh
script: "./travis/build.sh"
after_success:
- "./travis/publish.sh"
env:
  global:
  - GH_USER_NAME: robbl
  - GH_PROJECT_NAME: pandoc-travis-setup
  - GIT_AUTHOR_NAME: Travis
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - RESULT_PDF_PATH=$TRAVIS_BUILD_DIR/thesis.pdf
  - TZ="Europe/Zurich"
  - secure: Sz5XylYyMZPpjsFjYFV6G3CJGSdy+kLHDu+BsrRfnRYdTYokGbuakRoj/jBRgsPBoysBNw1h6PG0M6C6iPCWbwOVYeX69pM2+pSJqyBj+8Knk5/dczaGK78N25574l4c/T1OJm4Sb5I1+a1liWlYIPZR+UOmF6FMR/hmiZp7FClvahqbdoTmsE+3J1yPVx1fj3kJxIL6v8/qMzjJe1GkDR372WAp2nu7+7jVkS3m41zZepYvGXDF0JD4tACZ4pnYm5Uh/NchCLGKXvffz4iWxs4kIciOepyFLDBv2+hvpj1XUwIzmFDkB8vGKDRs/OpI7JXUIiaHPeQWpoS90E5FkC0S0hwjCRULtIb5JPTgzK+/xHNTNsOgQDxa0YziexL+6CF5Gqph7z4Z3+dRH+aSR4hxPddn8dqtM9wjvIo9QEq/42LAEYiXo8XCiyAbpQ5cV6kfEAlFY9NLIvjO07n7BoEtjS61DyhLb/8GGn54q7DB2m6VlGFxuxYidkm69Ff/SEnkp6y5+6bc9cVZFjvYySVHFQeQuff7riTYoNcY3YH38E/CpzOxTsYS9Kmp170Ksn8x3KlY9prsqLxx2hEC+QUkUv5PHPOAbbluUS3lCxHHcNEW2e+Ux0xaRhJQcK60L3IhEt2Xu/FIjRyzuNC9emQmHaBDyLe888f33bmHwYI=
